# Basisimage Python 3.12
FROM python:3.12-slim@sha256:d75c4b6cdd039ae966a34cd3ccab9e0e5f7299280ad76fe1744882d86eedce0b

# Install curl
RUN apt-get update && apt-get install -y curl

WORKDIR /src

# Python Packages installieren
COPY requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir -r /src/requirements.txt

# App in image kopieren
COPY src/app /src/app

# Daten für Indexing
COPY src/data /src/data

# Skript für RAG Querries
COPY src/scripts /src/scripts
RUN chmod +x /src/scripts/rag_queries.sh

# Embedding Modell
COPY emb_models /emb_models

# Port für FastAPI
EXPOSE 8000

# Start von API
CMD ["uvicorn", "app.api_server:app", "--host", "0.0.0.0", "--port", "8000"]
