### Frage 1
POST http://localhost:8000/ask
Content-Type: application/json; charset=utf-8

{
  "question": "What can you tell me about sustainability?"
}

### Frage 2
POST http://localhost:8000/ask
Content-Type: application/json; charset=utf-8

{
  "question": "What goals are being pursued to achieve greater sustainability?"
}

### Frage 3
POST http://localhost:8000/ask
Content-Type: application/json; charset=utf-8

{
  "question": "What is the European Green Deal?"
}

### Frage 4
POST http://localhost:8000/ask
Content-Type: application/json; charset=utf-8

{
  "question": "Can climate change still be stopped?"
}

### Frage 5
POST http://localhost:8000/ask
Content-Type: application/json; charset=utf-8

{
  "question": "What is a greenhouse gas and which one is most responsible for climate change?"
}